- name: configure zabbix agent
  copy:
    src: zabbix_configuration.conf # files directory is assumed
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: 0755

- name: start zabbix agent
  service: 
    name: zabbix-agent
    state: started
    enabled: yes